use_frameworks!

target 'RxSwiftCollections_Example' do
  
  inhibit_all_warnings!

  pod 'RxSwiftCollections', :path => '../'

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'DeepDiff',   '~> 1.2'

  target 'RxSwiftCollections_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    pod 'RxSwiftCollections', :path => '../'
  end
  
end
